# Generated by Django 4.2 on 2023-04-24 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class_level',
            options={'verbose_name': 'class_level', 'verbose_name_plural': 'class_levels'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'courses', 'verbose_name_plural': 'courses'},
        ),
        migrations.AlterModelOptions(
            name='lecture_session',
            options={'verbose_name': 'lecture_session', 'verbose_name_plural': 'lecture_sessions'},
        ),
        migrations.RenameField(
            model_name='student',
            old_name='current_level',
            new_name='class_level',
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('roll_no', 'class_level')},
        ),
    ]
